# Generated by Django 3.2 on 2021-05-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encyclopedia',
            fields=[
                ('title', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
